name: Build Native Images

on:
  push:
    branches: [ "main", "release/**" ]
  pull_request:
    branches: [ "main", "release/**" ]
  release:
    types: [ published ]

jobs:
  run:
   - name: "Checkout repository"
     uses: actions/checkout@v3
     with:
       submodules: recursive
   - name: "Package"
     uses: ".github/native-images-action/.github/workflows/native-build.yml"
     with:
       build: ./compiler/install
       test: ./compiler/test
       output-directory: ./compiler/bin
       meta-package: fpp
       fast-hack: true
     secrets: inherit
