name: Build Native Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]

jobs:
  run:
    name: "Package"
    uses: "fprime-community/native-images-action/.github/workflows/native-build.yml@main"
    with:
      build: ./compiler/install
      test: ./compiler/test
      output-directory: ./compiler/bin
      meta-package: fpp
      fast-hack: true
    secrets: inherit
